INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Electronics', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Computers', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Clothing', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Home & Kitchen', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Sports', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Toys', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Health', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Beauty', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Automotive', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Garden', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Pet Supplies', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Jewelry', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Watches', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Shoes', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Office Products', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Software', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Video Games', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Movies', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Music', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Baby', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Industrial & Scientific', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Tools & Home Improvement', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Luggage', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Musical Instruments', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Grocery', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Handmade', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Collectibles', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Fine Art', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Appliances', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Cell Phones & Accessories', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Personal Care', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Outdoors', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Art Supplies', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Camera & Photo', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Furniture', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Lighting', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Crafts & Sewing', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Bags', NOW());
INSERT INTO TB_CATEGORY(name, created_At) VALUES ('Office Furniture', NOW());